<!DOCTYPE html>
<html lang="fr">
<head>

	<meta charset="UTF-8">

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">

	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta name="robots" content="all">

	<!--<link rel="stylesheet" href="/projets/dewep/themes/css/global.css?1374821607" media="screen, projection" type="text/css">
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<link rel="icon" href="/favicon.ico" type="image/x-icon">
	<link rel="canonical" href="http://www.dewep.net/">
	<link rel="author" href="https://plus.google.com/100373771398479088953">--><!--publisher-->
	<!--<link rel="alternate" type="application/rss+xml" href="http://www.dewep.net/Blog/rss.xml" title="Flux RSS du blog de Dewep.net">-->

	<meta name="author" content="Maigret Aurélien">
	<meta name="keywords" content="dewep">
	<meta name="description" content="Description">
	<title>Claé Les Courlis</title>

	<!--<script type='text/javascript' src="/projets/common/themes/js/jquery-1.7.2.min.js"></script>-->

	<!--[if ie]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
	<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

</head>
<body>

	<?php $this->render('header'); ?>

	<?php $this->renderAction(); ?>

	<?php $this->render('footer'); ?>

</body>
</html>